# Generated by Django 5.2.8 on 2026-02-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teams_leader_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='チーム説明'),
        ),
    ]
