# Generated by Django 5.2.8 on 2026-01-25 03:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='スペースID')),
                ('name', models.CharField(max_length=150, verbose_name='スペース名')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='3桁の英数字のみ入力してください', regex='^[a-zA-Z0-9]{3}$')], verbose_name='スペースコード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'スペース',
                'verbose_name_plural': 'スペース',
                'db_table': 'Spaces',
            },
        ),
    ]
