# Generated by Django 5.2.8 on 2026-02-15 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_alter_spaces_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='英数字3文字で入力してください', regex='^[A-Z0-9]{3}$')], verbose_name='スペースコード'),
        ),
    ]
