# Generated by Django 5.2.8 on 2026-01-25 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('employee_id', models.CharField(max_length=15, verbose_name='社員ID')),
                ('login_id', models.CharField(max_length=18, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='ユーザー名')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理者権限設定')),
                ('is_profile_public', models.BooleanField(default=False, verbose_name='プライバシー設定')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'Users',
            },
        ),
    ]
