# Generated by Django 5.2.8 on 2026-02-14 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('spaces', '0002_alter_spaces_owner_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_user_space',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='spaces.spaces'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('login_id', 'space'), name='unique_user_space'),
        ),
    ]
