# Generated by Django 5.2.8 on 2026-02-15 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_unique_user_space_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('spaces', '0003_alter_spaces_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_user_space',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='英数字1文字から15文字で入力してください', regex='^[A-Z0-9]{1,15}$')], verbose_name='社員ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login_id',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.RegexValidator(message='英数字5文字から19文字で入力してください', regex='^[A-Z0-9]{5,19}$')]),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('employee_id', 'space'), name='unique_user_space'),
        ),
    ]
