# Generated by Django 5.2.8 on 2026-02-21 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_unique_user_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_id',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.RegexValidator(message='login_idの形式が不正です', regex='^[A-Z0-9]{3}_[A-Z0-9]{1,15}$')]),
        ),
    ]
