# Generated by Django 5.2.8 on 2026-01-28 05:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueMaster',
            fields=[
                ('value_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Value_Master',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='質問')),
                ('text', models.TextField()),
                ('is_reverse', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('value_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='analysis.valuemaster')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='UserValueScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ユーザー回答スコアID')),
                ('personal_score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(12)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_value_scores', to=settings.AUTH_USER_MODEL)),
                ('value_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_scores', to='analysis.valuemaster')),
            ],
            options={
                'db_table': 'user_value_scores',
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_value__user_id_939fcc_idx'), models.Index(fields=['user', 'value_key'], name='user_value__user_id_8e5157_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAdvice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ユーザーアドバイスID')),
                ('importance', models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低')], max_length=10)),
                ('is_minus_side', models.BooleanField(default=False)),
                ('advice_text', models.TextField()),
                ('value_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_advices', to='analysis.valuemaster')),
            ],
            options={
                'db_table': 'user_advices',
                'constraints': [models.UniqueConstraint(fields=('value_key', 'importance', 'is_minus_side'), name='unique_user_advice')],
            },
        ),
        migrations.CreateModel(
            name='TeamValueScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='チーム回答スコアID')),
                ('mean', models.FloatField()),
                ('max_diff', models.IntegerField()),
                ('std', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_value_scores', to='teams.teams')),
                ('value_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_scores', to='analysis.valuemaster')),
            ],
            options={
                'db_table': 'team_value_scores',
                'indexes': [models.Index(fields=['team', 'created_at'], name='team_value__team_id_91ad37_idx'), models.Index(fields=['team', 'value_key'], name='team_value__team_id_80881a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamAdvice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='チームアドバイスID')),
                ('code', models.CharField(choices=[('Q1_stable_harmony', '安定調和型'), ('Q2_deep_focus', '視点深化型'), ('Q3_partial_diversity', '部分多様型'), ('Q4_wide_diversity', '広域多様型')], max_length=30)),
                ('situation_text', models.TextField()),
                ('summary_text', models.TextField()),
                ('detail_text', models.TextField()),
                ('value_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_advices', to='analysis.valuemaster')),
            ],
            options={
                'db_table': 'team_advices',
                'constraints': [models.UniqueConstraint(fields=('value_key', 'code'), name='unique_team_advice')],
            },
        ),
    ]
