# Generated by Django 5.2.8 on 2026-01-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teamvaluescore',
            new_name='Team_Value__team_id_6e052d_idx',
            old_name='team_value__team_id_91ad37_idx',
        ),
        migrations.RenameIndex(
            model_name='teamvaluescore',
            new_name='Team_Value__team_id_518c11_idx',
            old_name='team_value__team_id_80881a_idx',
        ),
        migrations.RenameIndex(
            model_name='uservaluescore',
            new_name='User_Value__user_id_1bb227_idx',
            old_name='user_value__user_id_939fcc_idx',
        ),
        migrations.RenameIndex(
            model_name='uservaluescore',
            new_name='User_Value__user_id_c6d54a_idx',
            old_name='user_value__user_id_8e5157_idx',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Questions',
        ),
        migrations.AlterModelTable(
            name='teamadvice',
            table='Team_Advices',
        ),
        migrations.AlterModelTable(
            name='teamvaluescore',
            table='Team_Value_Scores',
        ),
        migrations.AlterModelTable(
            name='useradvice',
            table='User_Advices',
        ),
        migrations.AlterModelTable(
            name='uservaluescore',
            table='User_Value_Scores',
        ),
    ]
